#!/bin/bash

echo "RX module"
sa818 volume --port /dev/ttyAMA1 --level 1
#sa818 radio --port /dev/ttyAMA1 --frequency 145.025 --squelch 4
sa818 radio --port /dev/ttyAMA1 --frequency 438.800 --squelch 4
#sa818 radio --port /dev/ttyAMA1 --frequency 145.025 --ctcss 94.8,94.8
sa818 filters --port /dev/ttyAMA1 --emphasis no --highpass no --lowpass no


echo "TX module"
sa818 volume --port /dev/ttyAMA0 --level 1
#sa818 radio --port /dev/ttyAMA0 --frequency 145.025 --squelch 4
sa818 radio --port /dev/ttyAMA0 --frequency 431.200 --squelch 4
#sa818 radio --port /dev/ttyAMA0 --frequency 145.025 --ctcss 94.8,94.8
sa818 filters --port /dev/ttyAMA0 --emphasis no --highpass no --lowpass no
